kind: List
apiVersion: v1
metadata:
  name: amq-broker-7-image-streams
  annotations:
    description: ImageStream definitions for Red Hat AMQ Broker 7.9 Container Image
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: amq-broker
    annotations:
      openshift.io/display-name: Red Hat AMQ Broker 7.9
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    lookupPolicy:
      local: true  
    tags:
    - name: '7.9'
      annotations:
        description: Red Hat AMQ Broker 7.9.0 image.
        iconClass: icon-jboss
        tags: messaging,amq,jboss,xpaas
        supports: amq:7.9,messaging:7.9
        version: '7.9'
      from:
        kind: DockerImage
        name: registry.redhat.io/amq7/amq-broker:7.9
