apiVersion: apps/v1
kind: Deployment
metadata:
  name: statefulset-drain-controller-deployment
  labels:
    app: statefulset-drain-controller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefulset-drain-controller-app
  template:
    metadata:
      labels:
        app: statefulset-drain-controller-app
    spec:
      serviceAccountName: statefulset-drain-controller-sa
      containers:
      - name: main
        image: ${REGISTRY}/${PROJECT_NAMESPACE}/statefulset-drain-controller:latest
        args:
        - --localOnly
        - --v 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefulset-drain-controller-sa
  labels:
    app: statefulset-drain-controller-app
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: statefulset-drain-controller-role
  namespace: ${PROJECT_NAMESPACE}
  labels:
    app: statefulset-drain-controller-app
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: statefulset-drain-controller-rb
  namespace: ${PROJECT_NAMESPACE}
  labels:
    app: statefulset-drain-controller-app
subjects:
  - kind: ServiceAccount
    name: statefulset-drain-controller-sa
roleRef:
  kind: Role
  name: statefulset-drain-controller-role
  apiGroup: rbac.authorization.k8s.io

